#############################################################################
# Makefile for building: HelioxHelper
# Generated by qmake (2.01a) (Qt 4.8.6) on: Tue Jun 28 08:16:45 2016
# Project:  HelioxHelper.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile HelioxHelper.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		helioxhelper.cpp \
		writeConfig.cpp \
		qtoolbuttonwithevents.cpp \
		SingleApplication.cpp \
		qactionwithevents.cpp \
		wideiconsmenu.cpp \
		addnew.cpp moc_helioxhelper.cpp \
		moc_qtoolbuttonwithevents.cpp \
		moc_SingleApplication.cpp \
		moc_qactionwithevents.cpp \
		moc_addnew.cpp \
		qrc_Resource.cpp
OBJECTS       = main.o \
		helioxhelper.o \
		writeConfig.o \
		qtoolbuttonwithevents.o \
		SingleApplication.o \
		qactionwithevents.o \
		wideiconsmenu.o \
		addnew.o \
		moc_helioxhelper.o \
		moc_qtoolbuttonwithevents.o \
		moc_SingleApplication.o \
		moc_qactionwithevents.o \
		moc_addnew.o \
		qrc_Resource.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		HelioxHelper.pro
QMAKE_TARGET  = HelioxHelper
DESTDIR       = 
TARGET        = HelioxHelper

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_helioxhelper.h ui_about.h ui_addnew.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: HelioxHelper.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile HelioxHelper.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile HelioxHelper.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/HelioxHelper1.0.0 || $(MKDIR) .tmp/HelioxHelper1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/HelioxHelper1.0.0/ && $(COPY_FILE) --parents helioxhelper.h writeConfig.h qtoolbuttonwithevents.h SingleApplication.h qactionwithevents.h wideiconsmenu.h addnew.h .tmp/HelioxHelper1.0.0/ && $(COPY_FILE) --parents Resource.qrc .tmp/HelioxHelper1.0.0/ && $(COPY_FILE) --parents main.cpp helioxhelper.cpp writeConfig.cpp qtoolbuttonwithevents.cpp SingleApplication.cpp qactionwithevents.cpp wideiconsmenu.cpp addnew.cpp .tmp/HelioxHelper1.0.0/ && $(COPY_FILE) --parents helioxhelper.ui about.ui addnew.ui .tmp/HelioxHelper1.0.0/ && $(COPY_FILE) --parents tr/es_ES.ts tr/es_MX.ts tr/ca_ES.ts tr/gl_ES.ts tr/eu_ES.ts .tmp/HelioxHelper1.0.0/ && (cd `dirname .tmp/HelioxHelper1.0.0` && $(TAR) HelioxHelper1.0.0.tar HelioxHelper1.0.0 && $(COMPRESS) HelioxHelper1.0.0.tar) && $(MOVE) `dirname .tmp/HelioxHelper1.0.0`/HelioxHelper1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/HelioxHelper1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_helioxhelper.cpp moc_qtoolbuttonwithevents.cpp moc_SingleApplication.cpp moc_qactionwithevents.cpp moc_addnew.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_helioxhelper.cpp moc_qtoolbuttonwithevents.cpp moc_SingleApplication.cpp moc_qactionwithevents.cpp moc_addnew.cpp
moc_helioxhelper.cpp: qtoolbuttonwithevents.h \
		qactionwithevents.h \
		wideiconsmenu.h \
		helioxhelper.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) helioxhelper.h -o moc_helioxhelper.cpp

moc_qtoolbuttonwithevents.cpp: qtoolbuttonwithevents.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) qtoolbuttonwithevents.h -o moc_qtoolbuttonwithevents.cpp

moc_SingleApplication.cpp: SingleApplication.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) SingleApplication.h -o moc_SingleApplication.cpp

moc_qactionwithevents.cpp: qactionwithevents.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) qactionwithevents.h -o moc_qactionwithevents.cpp

moc_addnew.cpp: addnew.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) addnew.h -o moc_addnew.cpp

compiler_rcc_make_all: qrc_Resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Resource.cpp
qrc_Resource.cpp: Resource.qrc \
		tr/eu_ES.qm \
		tr/es_MX.qm \
		tr/ca_ES.qm \
		tr/gl_ES.qm \
		tr/es_ES.qm \
		images/about.png \
		images/minimize.png \
		images/restore.png \
		images/trayicon.png \
		images/quit.png \
		images/inali.png \
		images/SSCYDC.png \
		images/language.png \
		images/settings.png \
		images/lang/en_IE.png \
		images/lang/nah_MX.png \
		images/lang/en_US.png \
		images/lang/es_MX.png \
		images/lang/es_ES.png \
		images/lang/mig_MX.png \
		images/lang/ca_ES.png \
		images/lang/myn_MX.png \
		images/lang/que_PE.png \
		images/lang/en_GB.png
	/usr/lib/i386-linux-gnu/qt4/bin/rcc -name Resource Resource.qrc -o qrc_Resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_helioxhelper.h ui_about.h ui_addnew.h
compiler_uic_clean:
	-$(DEL_FILE) ui_helioxhelper.h ui_about.h ui_addnew.h
ui_helioxhelper.h: helioxhelper.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic helioxhelper.ui -o ui_helioxhelper.h

ui_about.h: about.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic about.ui -o ui_about.h

ui_addnew.h: addnew.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic addnew.ui -o ui_addnew.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp helioxhelper.h \
		qtoolbuttonwithevents.h \
		qactionwithevents.h \
		wideiconsmenu.h \
		writeConfig.h \
		SingleApplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

helioxhelper.o: helioxhelper.cpp helioxhelper.h \
		qtoolbuttonwithevents.h \
		qactionwithevents.h \
		wideiconsmenu.h \
		ui_helioxhelper.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helioxhelper.o helioxhelper.cpp

writeConfig.o: writeConfig.cpp writeConfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o writeConfig.o writeConfig.cpp

qtoolbuttonwithevents.o: qtoolbuttonwithevents.cpp qtoolbuttonwithevents.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtoolbuttonwithevents.o qtoolbuttonwithevents.cpp

SingleApplication.o: SingleApplication.cpp SingleApplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SingleApplication.o SingleApplication.cpp

qactionwithevents.o: qactionwithevents.cpp qactionwithevents.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qactionwithevents.o qactionwithevents.cpp

wideiconsmenu.o: wideiconsmenu.cpp wideiconsmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wideiconsmenu.o wideiconsmenu.cpp

addnew.o: addnew.cpp addnew.h \
		ui_addnew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addnew.o addnew.cpp

moc_helioxhelper.o: moc_helioxhelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_helioxhelper.o moc_helioxhelper.cpp

moc_qtoolbuttonwithevents.o: moc_qtoolbuttonwithevents.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtoolbuttonwithevents.o moc_qtoolbuttonwithevents.cpp

moc_SingleApplication.o: moc_SingleApplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SingleApplication.o moc_SingleApplication.cpp

moc_qactionwithevents.o: moc_qactionwithevents.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qactionwithevents.o moc_qactionwithevents.cpp

moc_addnew.o: moc_addnew.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addnew.o moc_addnew.cpp

qrc_Resource.o: qrc_Resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Resource.o qrc_Resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

